# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

services:
###########################
# Setup the Nginx container
###########################
    nginx:
        image: nginx:latest
        container_name: nginx_${HOSTNAME}
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
        volumes_from:
            - php

###########################
# Setup the PHP container
###########################
    php:
        build: ./docker/php/
        container_name: ${HOSTNAME}
        expose:
            - 9000
        volumes:
            - ./html:/var/www/html:delegated
            - ~/.ssh:/root/.ssh:cached
            - ~/.gitconfig:/root/.gitconfig:cached
    php_xdebug:
        build: ./docker/xdebug/
        container_name: xdebug_${HOSTNAME}
        expose:
            - 9000
        volumes:
            - ./html:/var/www/html:delegated
            - ~/.ssh:/root/.ssh:cached
            - ~/.gitconfig:/root/.gitconfig:cached

###########################
# Setup the Database (MySQL) container
###########################
    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql_${HOSTNAME}
        ports:
            - 3307:3306
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:cached
        environment:
            MYSQL_ROOT_PASSWORD: ${DBROOTPASSWORD}
            MYSQL_DATABASE: ${DB}
            MYSQL_USER: ${DBUSER}
            MYSQL_PASSWORD: ${DBPASSWORD}


###########################
# ELASTIC
###########################
    elasticsearch0:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
        container_name: elastic_${HOSTNAME}
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
