# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

volumes:
    database_data:
        driver: local

services:
###########################
# Setup the Nginx container
###########################
    nginx:
        image: nginx:latest
        container_name: nginx
        expose:
            - 80
        ports:
            - 80:80
            - 8080:80
            - 8081:81
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/:cached
        volumes_from:
            - php5
            - php7

###########################
# Setup the PHP 5x container
###########################
    php5:
        build: ./docker/php5x/
        container_name: php5
        expose:
            - 9000
        volumes:
            - /www/sites:/var/www/html:cached
            - ~/.ssh:/root/.ssh:cached
            - ~/.gitconfig:/root/.gitconfig:cached

###########################
# Setup the PHP 7x container
###########################
    php7:
        build: ./docker/php7x/
        container_name: php7
        expose:
            - 9000
        volumes:
            - /www/sites:/var/www/html:cached
            - ~/.ssh:/root/.ssh:cached
            - ~/.gitconfig:/root/.gitconfig:cached

###########################
# Setup the Database (MySQL) container
###########################
    mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - database_data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: project
