# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

volumes:
    database_data:
        driver: local

services:
###########################
# Setup the Nginx container
###########################
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

###########################
# Setup the PHP container
###########################
    php:
        build: ./docker/php/
        container_name: php
        expose:
            - 9000
        volumes:
            - ./html:/var/www/html

###########################
# Setup the Database (MySQL) container
###########################
    mysql:
        image: mysql:latest
        container_name: mysql
        #expose:
        #    - 3306
        ports:
        #     - 3307:3306
        - 3306:3306
        volumes:
            - database_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: project